fx_version "cerulean"
game "gta5"
author "OrigenNetwork"
version "2.5.8"

shared_scripts {
    "config/_framework.lua",
    "config/police-stations/loader.lua",
    "config/translations/cn.lua",
    "config/translations/en.lua",
    "config/translations/es.lua",
    "config/translations/fr.lua",
    "config/translations/hu.lua",
    "config/translations/it.lua",
    "config/translations/overrides/overrides.lua",
    "config/translations_bind.lua",
    "config/actions.lua",
    "config/alerts.lua",
    "config/armoury.lua",
    "config/badges.lua",
    "config/commands.lua",
    "config/confiscate.lua",
    "config/evidences.lua",
    "config/federal.lua",
    "config/handcuff.lua",
    "config/holster.lua",
    "config/jobs.lua",
    "config/k9.lua",
    "config/licenses.lua",
    "config/logs.lua",
    "config/markers.lua",
    "config/names.lua",
    "config/outfits.lua",
    "config/permissions.lua",
    "config/props.lua",
    "config/radio.lua",
    "config/references.lua",
    "config/reports.lua",
    "config/stashes.lua",
    "config/vehicles.lua",
    "radio/config.lua",
    "custom/shared/inventory.lua",
    "custom/shared/shared.lua",
}

client_scripts {
    "utils/mugshot.lua",
    "utils/streaming.lua",
    "hooks/client.lua",
    "custom/framework/client/esx.lua",
    "custom/framework/client/qb.lua",
    "custom/client/actions.lua",
    "custom/client/clothing.lua",
    "custom/client/evidences.lua",
    "custom/client/commands.lua",
    "custom/client/federal.lua",
    "custom/client/inventory.lua",
    "custom/client/menu.lua",
    "custom/client/rpol.lua",
    "custom/client/vehicles.lua",
    "custom/client/voice.lua",
    "custom/client/client_pay_bills.lua",
    "custom/client/_diagnostic.lua",
    "client/handlers/handlers.lua",
    "client/handlers/init.lua",
    "client/init.lua",
    "client/menu/main.lua",
    "client/menu/police.lua",
    "client/menu/radio.lua",
    "client/_maths.lua",
    "client/alpr.lua",
    "client/bind_system.lua",
    "client/cams.lua",
    "client/civilians.lua",
    "client/confiscate.lua",
    "client/dispatch.lua",
    "client/events.lua",
    "client/evidences.lua",
    "client/federal.lua",
    "client/functions.lua",
    "client/helicam.lua",
    "client/holster.lua",
    "client/interaction.lua",
    "client/k9.lua",
    "client/main.lua",
    "client/objects.lua",
    "client/placaje.lua",
    "client/references.lua",
    "client/settings.lua",
    "client/shapes.lua",
    "client/sirens.lua",
    "client/tracker.lua",
    "client/traffic.lua",
    "radio/client/events.lua",
    "radio/client/functions.lua",
    "radio/client/main.lua",
    "radio/client/modules/keys.lua",
    "radio/client/modules/manager.lua",
    "radio/client/modules/tables.lua",
}

server_scripts {
    "server/middlewares/00_security_shim.lua",
    "hooks/server.lua",
    "utils/FileManager.js",
    "server/middlewares/admin.lua",
    "config/logs/logs.lua",
    "custom/server/ban.lua",
    "custom/server/bills.lua",
    "custom/server/database.lua",
    "custom/framework/server/esx.lua",
    "custom/framework/server/qb.lua",
    "custom/server/inventory.lua",
    "custom/server/rpol.lua",
    "custom/server/society.lua",
    "custom/server/vehicles.lua",
    "custom/server/menu/structureManager.lua",
    "custom/server/menu/bank.lua",
    "custom/server/menu/bills.lua",
    "custom/server/menu/citizen.lua",
    "custom/server/menu/licenses.lua",
    "custom/server/menu/nationality.lua",
    "custom/server/menu/phone.lua",
    "custom/server/menu/properties.lua",
    "custom/server/menu/vehicles.lua",
    "custom/server/menu/weapons.lua",
    "custom/server/federal.lua",
    "server/init.lua",
    "server/callbacks.lua",
    "server/cams.lua",
    "server/central.lua",
    "server/clock.lua",
    "server/confiscate.lua",
    "server/dispatch.lua",
    "server/esx_duty.lua",
    "server/events.lua",
    "server/evidences.lua",
    "server/federal.lua",
    "server/interaction.lua",
    "server/items.lua",
    "server/licenses.lua",
    "server/logs.lua",
    "server/objects.lua",
    "server/penalcode.lua",
    "server/placaje.lua",
    "server/references.lua",
    "server/settings.lua",
    "server/shapes.lua",
    "server/sirens.lua",
    "server/tables.lua",
    "server/tracker.lua",
    "server/traffic.lua",
    "server/version_checker.lua",
    "server/menu/main.lua",
    "server/menu/police.lua",
    "radio/server/events.lua",
    "radio/server/functions.lua",
    "radio/server/modules/tables.lua",
}

ui_page 'html/index.html'

files {
    "config/police-stations/*.json",
    'html/index.html',
    'html/apps/*.html',
    'html/components/*.html',
    'html/img/*.*',
    'html/img/**/**',
    'html/img/webp/*.webp',
    'html/**/*.*',
    'html/sounds/*.*',
    'html/css/*.css',
    'html/fonts/*.*',
    'html/js/*.js',
    'stream/*.ytyp',
}

data_file 'DLC_ITYP_REQUEST' 'stream/*.ytyp'

provide {
    'qb-policejob'
}

lua54 'yes'

dependencies {
    "pma-voice"
}

escrow_ignore {
    "utils/mugshot.lua",
    "config/*.lua",
    "config/translations/*.lua",
    "config/logs/logs.lua",
    "custom/client/*.lua",
    "custom/client/menu/*.lua",
    "custom/framework/**/*.lua",
    "custom/shared/*.lua",
    "custom/server/*.lua",
    "custom/server/menu/*.lua",
    "server/tables.lua",
    "radio/config.lua",
    'items.lua'
}
